### ISSUE TITLE
报错，是和absl接不上嘛？

### ISSUE THREAD

**Issue by libsu** [paulhybryant/convertible_bond#1]
`I0706 19:33:21.221671 4605296128 main.py:99] https://www.jisilu.cn/data/cbnew/cb_list/?___jsl=LST___t=1625571201221
Traceback (most recent call last):
  File "/Users/libsu/Downloads/convertible_bond-main/main.py", line 262, in <module>
    app.run(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/Users/libsu/Downloads/convertible_bond-main/main.py", line 257, in main
    data = process(dat)
  File "/Users/libsu/Downloads/convertible_bond-main/main.py", line 214, in process
    cc_dict = get_cc()
  File "/Users/libsu/Downloads/convertible_bond-main/main.py", line 75, in get_cc
    with open(FLAGS.cc, 'r', encoding='utf-8') as cc_file:
FileNotFoundError: [Errno 2] No such file or directory: 'cc.csv'`

**Comment by paulhybryant** [comment]
不是，是你的目录下没有cc.csv这个文件。这个文件存储的是当前的持仓，以计算如何轮动。

**Comment by paulhybryant** [comment]
你把cc.csv换成另外一个文件名就好了。
